### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by rejas**
- use https
- update libs and urls
- cleanup css
- use pngs everywhere instead of jpg

### CODE REVIEW

**Comment by rejas** [comment]
pinging @MichMich  :-)

**Comment by MichMich** [comment]
Sorry. On holiday. Will look at it asap.

**Comment by rejas** [comment]
hi @MichMich still on holidays? ;-)

**Comment by MichMich** [comment]
Sorry. Was abroad for work. In the plane now. Will check tomorrow. 👍🏻😁

**Comment by rejas** [comment]
Internet on a plane? What time to be alive ;-)

**Comment by rejas** [comment]
Did you merge it from the plane???

**Comment by MichMich** [comment]
Merged and deployed at the airport. ;)

**Comment by rejas** [comment]
Missed an opprtunity for the "Merged from a fricking plane"-badge :-)

**Comment by MichMich** [comment]
Haha ... my next plane leaves in about 1,5 hours. If you make a new PR I'll make sure to merge it as soon as I'm airborne. 😂

**Comment by rejas** [comment]
You can take that one I guess: https://github.com/MichMich/MagicMirror/pull/3173

**Pull request merged**
